### ISSUE TITLE
Convert FSH to FHIR and back using right click context menu in the explorer view

### ISSUE THREAD

**Issue by hvamstel** [FHIR/vscode-fsh#96]
To allow for quick conversion of files to and from FSH using the explorer view.

**Example:**
Converting and JSON file that contains a FHIR resource to FSH by right clicking on this file in the explorer view and then select the option to convert it to FSH.

The same way of working for converting an existing FSH file to JSON FHIR.

The needed dependencies can be taken from the settings of the plugin as well as the needed fhir version when converting back to FHIR.

**Comment by mint-thompson** [comment]
Fixed by #97
